version: "2"
services:
  tests:
    build: .
    image: keboola/thoughtspot-writer
    volumes:
      - .:/code
    working_dir: /code
    command: >
      sh -c "composer install
      && ./vendor/bin/phpstan analyse src tests
      && ./vendor/bin/phpunit"
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - DB_DATABASE
      - SSH_USER
      - SSH_PASSWORD
