version: "2"
services:

  app:
    build: .
    image: keboola/wr-thoughtspot
    working_dir: /code
    volumes:
      - ./:/code
    command: bash
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - DB_DATABASE
      - SSH_USER
      - SSH_PASSWORD

  tests:
    build: .
    image: keboola/wr-thoughtspot
    working_dir: /code
    command: >
      sh -c "composer install
      && ./vendor/bin/phpstan analyse src tests"
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - DB_DATABASE
      - SSH_USER
      - SSH_PASSWORD
